/**
 * Created by santosh.sharma on 8/10/2018.
 */

const TRAVEL_TYPES = {
    UPDATE_COMPLETED_PROJECTS: 'UPDATE_COMPLETED_PROJECTS',
    CHANGE_USER_NAME: 'CHANGE_USER_NAME',
    USER_AUTHENTICATION: 'USER_AUTHENTICATION'
}

export default TRAVEL_TYPES;
